### PR TITLE
fix(ts): add ts and tsx to manifest script to support typescript, see #49

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by sibelius** [comment]
I'm not sure if this is enough to make fbt works on typescript react codebases

**Comment by jrwats** [comment]
I'm fine with this change, but we should probably parameterize anything going forward.  maybe an `exts` CLI option or something

**Comment by barakd** [comment]
any eta on merging this PR? would love to start using FBT but waiting for the typescript support

**Comment by jrwats** [comment]
@barakd, it's been there since February... was this comment for something else?

https://github.com/facebookincubator/fbt/blob/master/transform/babel-plugin-fbt/bin/manifest.js#L79

**Pull request closed without merging**
