### PR TITLE
android: upgrade rn-demo-app to RN 0.64.0

### PR DESCRIPTION
**Pull request by ecreeth**
## Summary
In [8fdbce6](https://github.com/facebook/fbt/commit/761eae6b1ff54e54d88a9a5ea9fb6119c0e4249d) the dependencies were updated to `0.64.0` but not in the Android native side.

- [x] update `android` code to `0.64.0`
- [x] update `react-native-fbt` to `0.0.5`
- [x] ~~added temporal fix to `react-native-fbt`. In version `0.0.3` this package has a mistake; its calling a file that doesn't exists in that location. The `js` directory is not found~~
https://github.com/facebook/fbt/blob/73468ad4ab6a2a754d739d98dd7ef1246619b9ee/packages/react-native-fbt/package.json#L6

#### Now the application build successfully
<table style="padding:10px">
  <tr>
    <td> 

   </td>
   <td>

   </td>
  </tr>
</table>

The `react-native-fbt` package needs to be updated to `0.0.3`. In new versions of React Native the `TurboModuleRegistry` is found in another destination, so the application will not compile.
https://github.com/facebook/fbt/blob/893492c5bb9349be532113741f8bb7c81aa473b0/packages/react-native-fbt/index.js#L22

This is resolved in `0.0.3`
https://github.com/facebook/fbt/blob/893492c5bb9349be532113741f8bb7c81aa473b0/packages/react-native-fbt/NativeFbtModule.js#L27

## Test plan
```bash
yarn android 
```

### CODE REVIEW

**Comment by ecreeth** [comment]
cc @hramos

**Comment by ecreeth** [comment]
I just update the `react-native-fbt` to `0.0.3` and added a temporal fix to it. Everything is OK now.
I'll send another PR to fix that issue.

**Comment by ecreeth** [comment]
@hramos bump version to [`0.0.4`](https://github.com/facebook/fbt/commit/54123a617dc6f22d9e35dfecf78d252035a73211) but is not published in npm yet. We need to use version 0.0.4 to build successful

**Comment by jrwats** [comment]
> @hramos bump version to [`0.0.4`](https://github.com/facebook/fbt/commit/54123a617dc6f22d9e35dfecf78d252035a73211) but is not published in npm yet. We need to use version 0.0.4 to build successful

`0.0.5` is published as of last week, heads up.

**Comment by ecreeth** [comment]
@jrwats is done!

**Comment by ecreeth** [comment]
@kayhadrin What's failing? Can I solve the problem or is it an internal-related issue?

**Comment by retyui** [comment]
More easily maintain RN updates by using [react-native-test-app](https://github.com/microsoft/react-native-test-app)

Here is a video of how it works in Microsoft https://www.youtube.com/watch?v=DAEnPV78rQc

**Comment by kayhadrin** [comment]
> @kayhadrin What's failing? Can I solve the problem or is it an internal-related issue?

Sorry it's been a while since this PR was submitted and it's getting rebase conflicts.
It'd be great to know if it's still needed nowadays.
cc: @hramos

**Pull request closed without merging**
