### PR TITLE
 Add package & Fix npm scripts to run demo-app properly

### PR DESCRIPTION
**Pull request by ifndefdeadmau5**
Seems `graceful-fs` package is missing from dependencies and npm scripts in `demo-app` is wrong.
I was able to run demo app after adding these changes.

### CODE REVIEW

**Comment by jrwats** [comment]
@ifndefdeadmau5 did you run `yarn install` or are you trying to use npm directly?  I think that's likely the source of the problem here...

**Comment by ifndefdeadmau5** [comment]
@jrwats Oh, my bad. I was expecting same result with `npm`, sorry!

**Comment by ifndefdeadmau5** [comment]
@jrwats This is totally off topic, but I'm wondering how your babel setup in demo-app is working with browser object(window, document, ...)?

I'm setting up fbt for my existing project, but when I run `yarn manifest` I keep getting a below error
> ReferenceError: window is not defined

**Comment by jrwats** [comment]
In `yarn manifest` that doesn't sound right...  do you have a line number or stack trace?

**Comment by ifndefdeadmau5** [comment]
@jrwats Sure, this is the full stack trace when run `yarn manifest`
```
~/github/balancebrain/bb-center-web-platform(feature/i18n*) » yarn manifest                                         bagseongmin@bagseongmins-iMac
yarn run v1.13.0
$ babel-node transform/babel-plugin-fbt/bin/manifest --src react
/Users/bagseongmin/github/balancebrain/bb-center-web-platform/transform/babel-plugin-fbt/bin/manifest.js:80
      throw _iteratorError;
      ^

ReferenceError: document is not defined
    at Object.document (/Users/bagseongmin/github/balancebrain/bb-center-web-platform/react/index.js:6:26)
    at Module._compile (module.js:652:30)
    at Module._compile (/Users/bagseongmin/github/balancebrain/bb-center-web-platform/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/bagseongmin/github/balancebrain/bb-center-web-platform/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jrwats** [comment]
line [80?](https://github.com/facebookincubator/fbt/blob/master/transform/babel-plugin-fbt/bin/manifest.js#L80)
Have you run a `git pull` on the repo recently? I'd be very surprised if `String.trim` was causing iteratorError.  Something definitely seems weird.

**Comment by ifndefdeadmau5** [comment]
@jrwats Ah, I didn't notice the `manifest.js` change! So it was line [64](https://github.com/facebookincubator/fbt/blob/master/transform/babel-plugin-fbt/bin/manifest.js#L64), but I'd better try with new version.

**Pull request closed without merging**
